---

# This is the list of files that contain the arguments to Marathon.
# The mesosphere package we're using has the weird requirement that each
# commandline argument to marathon be present in its own file under /etc/marathon directory
# i.e to pass argument foo=bar, we need to have a file named foo with contents of bar
# under /etc/marathon directory.
marathon_args_files:
  - event_subscriber
  - hostname
  - master
  - max_apps
  - task_launch_timeout
  - zk

marathon_auth_args_files:
  - plugin_conf
  - plugin_dir

old_marathon_package_deps:
  - openjdk-7-jre-headless
  - openjdk-7-jre
  - openjdk-7-jdk

marathon_package_deps:
  - ca-certificates-java
  - tzdata-java
  - java-common
  - libcurl3
  - libsvn1
  - fontconfig-config
  - fonts-dejavu-core
  - libasyncns0
  - libavahi-client3
  - libavahi-common-data
  - libavahi-common3
  - libcups2
  - libflac8
  - libfontconfig1
  - libjpeg-turbo8
  - libjpeg8
  - liblcms2-2
  - libnspr4
  - libnss3
  - libnss3-nssdb
  - libogg0
  - libpcsclite1
  - libpulse0
  - libsndfile1
  - libvorbis0a
  - libvorbisenc2

marathon_version: 0.15.3-1.0.463.ubuntu1404

marathon_auth_plugin_pkg: marathon_auth_plugin_0.1-alpha.tar.gz

marathon_auth_plugin_url: https://github.com/seomoz/marathon-auth-plugin/releases/download/v0.1-alpha/{{marathon_auth_plugin_pkg}}

marathon_auth_plugin_pkg_sha256: 7f26d8a1ffe47215d7ba4574852fa943efc0e34402f7d7bedd79e00cbe0e4156

marathon_auth_plugin_location: "{{base_data_dir}}/marathon/plugins"
